import type { AttackScenario } from "./types";
import { PHASE_LABELS, PHASE_ORDER } from "./types";

function download(filename: string, content: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
}

export function exportScenarioAsJson(scenario: AttackScenario) {
  const filename = `breachmind-scenario-${Date.now()}.json`;
  download(filename, JSON.stringify(scenario, null, 2), "application/json");
}

export function exportScenarioAsMarkdown(scenario: AttackScenario) {
  const lines: string[] = [];
  lines.push(`# BreachMind Threat Emulation Report`);
  lines.push("");
  lines.push(`**Target Stack:** ${scenario.target}`);
  lines.push(`**Generated:** ${new Date(scenario.generatedAt).toLocaleString()}`);
  lines.push(`**Source:** ${scenario.isFallback ? "Offline sample dataset" : scenario.sourceModel ?? "AI-generated"}`);
  lines.push("");
  lines.push(`## Executive Summary`);
  lines.push("");
  lines.push(scenario.summary);
  lines.push("");

  for (const phase of PHASE_ORDER) {
    const nodes = scenario.nodes.filter((n) => n.phase === phase);
    if (nodes.length === 0) continue;

    lines.push(`## ${PHASE_LABELS[phase]}`);
    lines.push("");

    for (const node of nodes) {
      lines.push(`### ${node.title}`);
      lines.push("");
      lines.push(`- **MITRE ATT&CK:** \`${node.mitreId}\` — ${node.mitreTactic}`);
      lines.push(`- **Severity:** ${node.severity}`);
      lines.push(`- **Tools:** ${node.tools.length ? node.tools.join(", ") : "N/A"}`);
      if (node.dependsOn && node.dependsOn.length) {
        lines.push(`- **Depends On:** ${node.dependsOn.join(", ")}`);
      }
      lines.push("");
      lines.push(`**Attack Vector Description**`);
      lines.push("");
      lines.push(node.description);
      lines.push("");
      lines.push(`**Executable Command / Payload**`);
      lines.push("");
      lines.push("```bash");
      lines.push(node.command);
      lines.push("```");
      lines.push("");
      lines.push(`**Blue Team Remediation**`);
      lines.push("");
      lines.push(node.remediation);
      lines.push("");
      lines.push("---");
      lines.push("");
    }
  }

  lines.push(`_Generated by BreachMind — AI-Powered Threat Emulation & Attack Flow Generator. For authorized security testing and blue-team training purposes only._`);

  const filename = `breachmind-report-${Date.now()}.md`;
  download(filename, lines.join("\n"), "text/markdown");
}
